# Generated by Django 4.1.1 on 2022-09-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intendance', '0002_alter_profile_bio_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
