# Generated by Django 4.1.1 on 2022-10-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intendance', '0003_notificationuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationuser',
            old_name='created_by',
            new_name='created_date',
        ),
    ]
