# Generated by Django 4.1.1 on 2022-10-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intendance', '0007_discussions'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussions',
            name='posted_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
