# Generated by Django 4.1.1 on 2022-10-22 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intendance', '0008_discussions_posted_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussions',
            old_name='user',
            new_name='posted_by',
        ),
    ]
