# Generated by Django 4.1.1 on 2022-10-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intendance', '0011_remove_project_invitation_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_invitation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project_invitation',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
